### PR TITLE
quick win fixes

### LINKED ISSUE #188: include departure in directions response
the directions endpoint only includes the duration of the route, not the departure time which makes it difficult to work with on the client side

### LINKED ISSUE #208: rename route response to directions
Currently the directions endpoint returns a route edn object.

The problem with this is that the GTFS directly also defines a route object, making the response ambiguous

### LINKED ISSUE #209: remove namespaces from Json responses
I thought it would be a good idea to make the json responses to include the namespace as well as the edn version. 

However this creates a very redundant and difficult to parse object.

The drawback of not having namespaces is that we can have key collisions ... But I think that is a Problem for another day

### PR DESCRIPTION
**Pull request by carocad**
- fixes #188 - step/departure spec added
- fixes #209 - dont namespace json responses
- fixes #208 - renamed route to directions to avoid name clash with gtfs

### CODE REVIEW

File: src/hiposfer/kamal/libs/tool.clj [hunk 1]
```diff
@@ -68,55 +68,23 @@
...
-   (json-namespace {:a (ZoneId/of \"Europe/Berlin\") :c/b [:d.e :f/g]}
-                   (keys edn/java-readers))
-   => {:a \"Europe/Berlin\", :c {:b ((:d :e) (:f :g))}} "
+(defn- stringify?
+  "only stringifies java object which are not primities (java.lang...)"
+  [^Object value]
+  (and (str/starts-with? (.getCanonicalName (.getClass ^Object value)) "java")
+       (not (str/starts-with? (.getCanonicalName (.getClass ^Object value)) "java.lang"))))
+
+(defn jsonista
```
Comment (mehdisadeghi) [inline src/hiposfer/kamal/libs/tool.clj]: Cool naming :)
